############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "blog/" #antes era /
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Search"
hasChildren = true

  [[main]]
  parent = "Search"
  name = "Posts"
  url = "search/"
  
  [[main]]
  parent = "Search"
  name = "Categories"
  url = "categories/"

  #[[main]]
  #name = "Elements"
  #url = "elements/"
  #weight = 4
  
  #[[main]]
  #parent = "Pages"#para criar um menu com submenus
  #name = "Pages"
  #url = "blog/"

  #[[main]]
  #parent = "Pages"
  #name = "Contact"
  #url = "contact/"

  #[[main]]
  #parent = "Pages"
  #name = "Authors"
  #url = "authors/"

  #[[main]]
  #parent = "Pages"
  #name = "404 Page"
  #url = "404/"


# footer menu
[[footer]]
name = "Authors"
url = "authors/"
weight = 1

#[[footer]]
#name = "Elements"
#url = "elements/"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3